// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using fitnessCenter.web.Data;

#nullable disable

namespace fitnessCenter.web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServiceTrainer", b =>
                {
                    b.Property<int>("ServicesId")
                        .HasColumnType("integer");

                    b.Property<int>("TrainersId")
                        .HasColumnType("integer");

                    b.HasKey("ServicesId", "TrainersId");

                    b.HasIndex("TrainersId");

                    b.ToTable("ServiceTrainer");
                });

            modelBuilder.Entity("fitnessCenter.web.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FitnessCenterId")
                        .HasColumnType("integer");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrainerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FitnessCenterId");

                    b.HasIndex("MemberId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("TrainerId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("fitnessCenter.web.Models.FitnessCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<TimeOnly?>("CalismaBaslangic")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("CalismaBitis")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.ToTable("FitnessCenters");
                });

            modelBuilder.Entity("fitnessCenter.web.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int>("FitnessCenterId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FitnessCenterId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("fitnessCenter.web.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FitnessCenterId")
                        .HasColumnType("integer");

                    b.Property<int>("SureDakika")
                        .HasColumnType("integer");

                    b.Property<decimal>("Ucret")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FitnessCenterId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("fitnessCenter.web.Models.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FitnessCenterId")
                        .HasColumnType("integer");

                    b.Property<string>("UzmanlikNotu")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FitnessCenterId");

                    b.ToTable("Trainers");
                });

            modelBuilder.Entity("fitnessCenter.web.Models.TrainerAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("TrainerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainerAvailabilities");
                });

            modelBuilder.Entity("ServiceTrainer", b =>
                {
                    b.HasOne("fitnessCenter.web.Models.Service", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fitnessCenter.web.Models.Trainer", null)
                        .WithMany()
                        .HasForeignKey("TrainersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("fitnessCenter.web.Models.Appointment", b =>
                {
                    b.HasOne("fitnessCenter.web.Models.FitnessCenter", null)
                        .WithMany("Appointments")
                        .HasForeignKey("FitnessCenterId");

                    b.HasOne("fitnessCenter.web.Models.Member", "Member")
                        .WithMany("Appointments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fitnessCenter.web.Models.Service", "Service")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fitnessCenter.web.Models.Trainer", "Trainer")
                        .WithMany("Appointments")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Service");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("fitnessCenter.web.Models.Member", b =>
                {
                    b.HasOne("fitnessCenter.web.Models.FitnessCenter", "FitnessCenter")
                        .WithMany("Members")
                        .HasForeignKey("FitnessCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FitnessCenter");
                });

            modelBuilder.Entity("fitnessCenter.web.Models.Service", b =>
                {
                    b.HasOne("fitnessCenter.web.Models.FitnessCenter", null)
                        .WithMany("Services")
                        .HasForeignKey("FitnessCenterId");
                });

            modelBuilder.Entity("fitnessCenter.web.Models.Trainer", b =>
                {
                    b.HasOne("fitnessCenter.web.Models.FitnessCenter", "FitnessCenter")
                        .WithMany("Trainers")
                        .HasForeignKey("FitnessCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FitnessCenter");
                });

            modelBuilder.Entity("fitnessCenter.web.Models.TrainerAvailability", b =>
                {
                    b.HasOne("fitnessCenter.web.Models.Trainer", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("fitnessCenter.web.Models.FitnessCenter", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Members");

                    b.Navigation("Services");

                    b.Navigation("Trainers");
                });

            modelBuilder.Entity("fitnessCenter.web.Models.Member", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("fitnessCenter.web.Models.Service", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("fitnessCenter.web.Models.Trainer", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
